import { CommandEvent, Result } from "../../types";
import { Commands } from "../../index.js";

let commandEvent: CommandEvent | any = {
  app: {
    _id: "68d11f0322e5865ce90326fe",
    name: "SAP Integration ",
    disabled: false,
    available_app: {
      _id: "639ee4cf462a9df7c25cef4c",
      name: "repzo-sap-absjo",
      title: "SAP ABS JO",
      logo: "https://prod-repzo-media-service.s3.us-east-1.amazonaws.com/repzo/image/2022/12/18/3f73de7d-1920-4786-90db-57c76d18acci-SAP_EBS_JO.png",
      description:
        "SAP Jordan. We provide real value to SMEs by understanding their business and driving their vision forward with SAP Business One",
      disabled: false,
      JSONSchema: {
        title: "SAP Integration Settings",
        type: "object",
        required: ["repzoApiKey", "sapHostUrl"],
        properties: {
          repzoApiKey: { type: "string", title: "Repzo API KEY" },
          sapHostUrl: { type: "string", title: "SAP Host Url" },
          errorEmail: {
            type: "string",
            format: "email",
            title: "Email in case of error",
          },
          GroupCode: {
            type: "string",
            format: "string",
            title: "Customers GroupCode",
          },
          warehouseDefaultUpdateDate: {
            type: "string",
            format: "date",
            title: "Warehouse: Default Update Date",
          },
          DepartmentCode: {
            type: "string",
            format: "string",
            title: "Invoice/Return Department Code",
          },
          return_reasons: {
            type: "string",
            format: "string",
            title: "Return Reason Array",
          },
          measureUnitInjections: {
            type: "string",
            format: "string",
            title:
              'Uom Injection Array, example: [{ "itemCode": "010-KEA-JU0003", "uom": "PC" }]',
          },
          defaultWarehouseForSalesOrder: {
            type: "string",
            format: "string",
            title: "Default Warehouse Code For Sales Orders",
          },
          SalPersCode: {
            type: "string",
            format: "string",
            title: "Default Sales Person Code For Sales Orders",
          },
          SalesPersonCode: {
            type: "string",
            format: "string",
            title: "Default Sales Person Code For Transfer",
          },
          invoices: {
            type: "object",
            title: "Invoices",
            required: ["createInvoiceHook", "createReturnInvoiceHook"],
            properties: {
              createInvoiceHook: {
                type: "boolean",
                title: "Live Sync Invoices from Repzo to SAP",
                default: false,
              },
              createReturnInvoiceHook: {
                type: "boolean",
                title: "Live Sync Return Invoice from Repzo to SAP",
                default: false,
              },
            },
          },
          payments: {
            type: "object",
            title: "Payments",
            required: ["createPaymentHook"],
            properties: {
              createPaymentHook: {
                type: "boolean",
                title: "Live Sync Payments from Repzo to SAP",
                default: false,
              },
            },
          },
          proformas: {
            type: "object",
            title: "Sales Orders",
            required: ["createApprovedProformaHook"],
            properties: {
              createApprovedProformaHook: {
                type: "boolean",
                title: "Live Sync Approved Sales Orders from Repzo to SAP",
                default: false,
              },
            },
          },
          transfers: {
            type: "object",
            title: "Transfers",
            required: ["createApprovedTransferHook"],
            properties: {
              createApprovedTransferHook: {
                type: "boolean",
                title: "Live Sync Approved Transfers from Repzo to SAP",
                default: false,
              },
              adjustInventoryInFailedTransfer: {
                type: "boolean",
                title:
                  "Adjust Inventories in Repzo if creation Transfer Failed in SAP",
                default: false,
              },
            },
          },
          client: {
            type: "object",
            title: "Client",
            required: ["createClientHook"],
            properties: {
              createClientHook: {
                type: "boolean",
                title: "Live Sync Clients from Repzo to SAP",
                default: false,
              },
            },
          },
        },
      },
      options_JSONSchema: {
        title: "SAP Integration Optional Settings",
        type: "object",
        required: [],
        properties: {
          bench_time_warehouse: {
            title: "Bench Time: Warehouse",
            type: "string",
            format: "date",
          },
          bench_time_channel: {
            title: "Bench Time: Channels",
            type: "string",
            format: "date-time",
          },
          bench_time_payment_term: {
            title: "Bench Time: Payment Terms",
            type: "string",
            format: "date-time",
          },
          bench_time_product: {
            title: "Bench Time: Products",
            type: "string",
            format: "date-time",
          },
          bench_time_product_disabled: {
            title: "Bench Time: Inactive Products",
            type: "string",
            format: "date-time",
          },
          bench_time_price_list: {
            title: "Bench Time: Price List",
            type: "string",
            format: "date-time",
          },
          bench_time_client: {
            title: "Bench Time: Clients",
            type: "string",
            format: "date-time",
          },
          bench_time_disabled_client: {
            title: "Bench Time: Inactive Clients",
            type: "string",
            format: "date-time",
          },
        },
      },
      app_settings: {
        repo: "",
        serviceEndPoint: "",
        _id: "639ee4cf462a9df7c25cef4d",
      },
      app_category: "629c62fcff7a8a2dc7a21ba1",
      commands: [
        {
          command: "basic",
          name: "Full Sync",
          description: "Exclude Join & Adjust Inventories",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef4e",
        },
        {
          command: "join",
          name: "Join",
          description: "",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef4f",
        },
        {
          command: "warehouse",
          name: "Sync Warehouse",
          description: "Sync Warehouses From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef50",
        },
        {
          command: "rep",
          name: "Sync Representatives",
          description: "Sync Representatives From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef51",
        },
        {
          command: "tax",
          name: "Sync Taxes",
          description: "Sync Taxes From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef52",
        },
        {
          command: "tag",
          name: "Sync Area Tags",
          description: "Sync Area Tags From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef53",
        },
        {
          command: "measureunit",
          name: "Sync Measure Units",
          description: "Sync Measure Units From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef54",
        },
        {
          command: "measureunit_family",
          name: "Sync Measure Units Family",
          description: "Sync Measure Units Family From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef55",
        },
        {
          command: "category",
          name: "Sync Product Category",
          description: "Sync Product Categories From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef56",
        },
        {
          command: "brand",
          name: "Sync Product Brand",
          description: "Sync Product Brands From SAP to Repzo",
          group_sync: false,
          _id: "63984085edafde008af2f689",
        },
        {
          command: "channel",
          name: "Sync Client's Channels",
          description: "Sync Client's Channels From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef57",
        },
        {
          command: "payment_term",
          name: "Sync Payments Term",
          description: "Sync Payments Term From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef58",
        },
        {
          command: "bank",
          name: "Sync Banks",
          description: "Sync Banks From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef59",
        },
        {
          command: "product",
          name: "Sync Products",
          description: "Sync Active Products From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef5a",
        },
        {
          command: "disabled_product",
          name: "Sync Inactive Products",
          description: "Sync Inactive Products From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef5b",
        },
        {
          command: "price_list",
          name: "Sync Price Lists",
          description: "Sync Price Lists From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef5c",
        },
        {
          command: "price_list_disabled",
          name: "Sync Disbaled Price List Items",
          description: "Sync Disbaled Price List Items From SAP to Repzo",
          group_sync: false,
          _id: "656ed4098961a3f97182773f",
        },
        {
          command: "client",
          name: "Sync Clients",
          description: "Sync Clients From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef5d",
        },
        {
          command: "disabled_client",
          name: "Sync Inactive Clients",
          description: "Sync Inactive Clients From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef5e",
        },
        {
          command: "adjust_inventory",
          name: "Adjust Inventories",
          description: "Adjust Inventories From SAP to Repzo",
          group_sync: false,
          _id: "639ee4cf462a9df7c25cef5f",
        },
      ],
      actions: [
        {
          action: "create_invoice",
          name: "Sync Invoices",
          description: "Sync Invoices From Repzo to SAP",
          _id: "639ee4cf462a9df7c25cef60",
        },
        {
          action: "create_return_invoice",
          name: "Sync Return Invoices",
          description: "Sync Return Invoices From Repzo to SAP",
          _id: "639ee4cf462a9df7c25cef61",
        },
        {
          action: "create_proforma",
          name: "Sync Approved Sales Orders",
          description: "Sync Approved Sales Orders From Repzo to SAP",
          _id: "639ee4cf462a9df7c25cef62",
        },
        {
          action: "create_payment",
          name: "Sync Paymants",
          description: "Sync Paymants From Repzo to SAP",
          _id: "639ee4cf462a9df7c25cef63",
        },
        {
          action: "create_transfer",
          name: "Sync Approved Transfers",
          description: "Sync Approved Transfers From Repzo to SAP",
          _id: "639ee4cf462a9df7c25cef64",
        },
        {
          action: "create_client",
          name: "Sync Approved Clients",
          description: "Sync Approved Clients From Repzo to SAP",
          _id: "68edeaa0bfbb2c273b91736f",
        },
      ],
      createdAt: "2022-12-18T10:00:47.414Z",
      updatedAt: "2025-10-14T06:16:00.977Z",
      __v: 0,
      subscription_billing_mode: "free",
    },
    company_namespace: ["hassanein1"],
    formData: {
      repzoApiKey: "SZx76pM2TiuFt9kK7fsBCLkW7oY8qA8pIjUHdmgzdZg",
      sapHostUrl: "https://abs-dmz.b1pro.com:9001/api",
      invoices: { createInvoiceHook: true, createReturnInvoiceHook: true },
      payments: { createPaymentHook: true },
      proformas: { createApprovedProformaHook: true },
      transfers: {
        createApprovedTransferHook: true,
        adjustInventoryInFailedTransfer: true,
      },
      client: { createClientHook: true },
    },
    options_formData: {
      bench_time_warehouse: "2025-01-01",
      bench_time_channel: "2025-09-22T11:59:38.667Z",
      bench_time_payment_term: "2025-09-24T09:04:47.049Z",
      bench_time_product: "2025-10-06T10:10:13.619Z",
      bench_time_price_list: "2025-10-14T11:00:40.686Z",
      bench_time_client: "2025-10-14T11:20:40.049Z",
      bench_time_rep: "2025-10-12T10:40:25.535Z",
      bench_time_tax: "2025-09-22T12:05:46.901Z",
      bench_time_tag: "2025-09-22T12:06:01.041Z",
      bench_time_measureunit: "2025-10-06T10:16:06.878Z",
      bench_time_measureunit_family: "2025-09-29T13:21:39.534Z",
      bench_time_category: "2025-09-24T09:04:43.969Z",
      bench_time_brand: "2025-09-22T11:59:36.800Z",
      bench_time_price_list_disabled: "2025-09-22T12:23:39.010Z",
    },
    createdAt: "2025-09-22T10:03:47.010Z",
    updatedAt: "2025-10-14T11:20:48.859Z",
    __v: 0,
  },
  end_of_day: "04:00",
  nameSpace: ["hassanein1"],
  timezone: "Asia/Amman",
  meta: "",
  env: "staging",
  sync_id: "bacad499-81e4-4925-bba4-b1f0befb7b21",
  command: "join",
};

Commands(commandEvent);
