import { Actions } from "../../index.js";
Actions(
  {
    version: "2.0",
    routeKey: "POST /actions",
    rawPath: "/actions",
    rawQueryString: "app=repzo-sap-absjo&action=create_client",
    headers: {
      action_sync_id: "Actions-0000004", // SYNC_ID
      accept: "*/*",
      "accept-encoding": "gzip, deflate",
      "content-length": "3658",
      "content-type": "application/json",
      host: "staging.marketplace.api.repzo.me",
      "svix-id": "msg_29I1By29ETyPiZ4SNrc99KIg7D6",
      "svix-signature": "v1,OkktM+dibxzeb0M6383POFjBr7DX14HECpBIh17FQnU=",
      "svix-timestamp": "1652785653",
      "user-agent": "Svix-Webhooks/1.4",
      "x-amzn-trace-id": "Root=1-628381f6-0b2c6f346d2eb5d207b582ee",
      "x-forwarded-for": "52.215.16.239",
      "x-forwarded-port": "443",
      "x-forwarded-proto": "https",
    },
    queryStringParameters: {
      action: "create_client",
      app: "repzo-sap-absjo",
    },
    requestContext: {
      accountId: "478266140170",
      apiId: "ulkb1ikop2",
      domainName: "staging.marketplace.api.repzo.me",
      domainPrefix: "staging",
      http: {
        method: "POST",
        path: "/actions",
        protocol: "HTTP/1.1",
        sourceIp: "52.215.16.239",
        userAgent: "Svix-Webhooks/1.4",
      },
      requestId: "SRE-ejb6IAMEPWQ=",
      routeKey: "POST /actions",
      stage: "$default",
      time: "17/May/2022:11:07:34 +0000",
      timeEpoch: 1652785654069,
    },
    body: JSON.stringify({
      company_namespace: ["hassanein1"],
      name: "علي عباس - مشتريات خاصه",
      tags: [],
      cell_phone: null,
      city: null,
      client_code: "CL01809",
      contact_name: null,
      contacts: [],
      country: null,
      disabled: false,
      formatted_address: null,
      geoPoint: { type: "Point", coordinates: [0, 0] },
      lat: 0,
      lng: 0,
      location_verified: false,
      phone: null,
      state: null,
      assigned_to: [],
      profile_pic: null,
      logo: null,
      website: "",
      email: "",
      comment: null,
      parent_client_id: null,
      target_visit: 0,
      geofencing_radius: null,
      price_tag: null,
      status: null,
      job_category: [],
      availability_msl: [],
      territory: null,
      sv_priceList: "68d13d4ed11f86a126325552",
      assigned_media: [],
      assigned_products: [],
      assigned_product_groups: [],
      financials: { credit_limit: 1000000000 },
      paymentTerm: "68d13a09196089cdda21115f",
      speciality: [],
      channel: "68d13a05aec62a4ccf654e8e",
      teams: [],
      payment_type: "cash",
      integration_meta: {
        id: "hassanein1_CL01809",
        PAYMENTTERM: 0,
        CLIENTCREDITCONSUMED: 18000,
        CLIENTMAXCHEQUEVALUE: 1500000,
        CLIENTCREDITLIMIT: 1500000,
        CLIENTPRICELISTID: 2,
      },
      integrated_client_balance: 18000000,
      media: [],
      invoice_balance_limit: 0,
      payment_terms_grace_period_days: 0,
      enable_invoice_balance_limit: false,
      enable_payment_terms_grace_period_days: false,
      enable_credit_limit_on_invoice: false,
      enable_credit_limit_on_proforma: false,
      enable_invoice_balance_limit_on_proforma: false,
      enable_payment_terms_grace_period_days_on_proforma: false,
      is_simplified: true,
      retail_execution_templates: [],
      assigned_forms_v2_templates: [],
      _id: "68ee2dd948dd6ab6d549ee9f",
      rep_targets: [],
      shelf_share_targets: [],
      jobs: [],
      createdAt: "2025-10-14T11:02:49.674Z",
      updatedAt: "2025-10-14T11:02:49.674Z",
      __v: 0,
    }),
    isBase64Encoded: false,
  },
  {
    app_id: "",
    repzoEndPoint: "",
    serviceEndPoint: "",
    env: "staging",
    data: {
      invoices: { createInvoiceHook: false, createReturnInvoiceHook: false },
      payments: { createPaymentHook: false },
      proformas: { createApprovedProformaHook: false },
      transfer: { createApprovedTransferHook: false },
      client: { createClientHook: true },
      repzoApiKey: "SZx76pM2TiuFt9kK7fsBCLkW7oY8qA8pIjUHdmgzdZg",
      sapHostUrl: "https://abs-dmz.b1pro.com:9001/api",
      errorEmail: "maram.alshen@repzoapp.com",
      serviceApiKey: "awdas",
      warehouseDefaultUpdateDate: "",
      DepartmentCode: "",
      return_reason: "",
      SalPersCode: "",
      SalesPersonCode: "",
    },
  }
);
